FROM golang:1.20-alpine AS build-env
WORKDIR /go/src/github.com/rusik69/ds0
COPY . ./
RUN go get ./...
RUN CGO_ENABLED=0 \
    go build -o /go/bin/client cmd/client/main.go

FROM alpine:latest
WORKDIR /app
COPY --from=build-env /go/bin/client /app/client

ENTRYPOINT ["/app/ns"]