FROM alpine

FROM golang:1.18-alpine AS build-env
WORKDIR /go/src/github.com/rusik69/ds0
COPY . ./
RUN go get ./...
RUN CGO_ENABLED=0 GOOS=linux GOARCH=arm64 \
    go build -o /go/bin/ns cmd/ns/main.go

FROM alpine:latest
WORKDIR /app
COPY --from=build-env /go/bin/ns /app/ns

ENTRYPOINT ["/app/ns"]
EXPOSE 6969