apiVersion: v1
kind: Pod
metadata:
  name: ds0-client
spec:
  nodeSelector:
    kubernetes.io/arch: amd64
  containers:
  - name: {{ include "ds0.fullname" . }}-client
    image: "{{ .Values.image.repositoryClient }}:{{ .Values.image.tag }}"
    command: ["/bin/sh", "-c", "sleep 99999999"]