apiVersion: v1
kind: Service
metadata:
  name: {{ include "ds0.fullname" . }}-node-headless
  labels:
    app: {{ include "ds0.name" . }}-node
spec:
  ports:
  - port: 6969
    name: {{ include "ds0.fullname" . }}-node
  clusterIP: None
  selector:
    app: {{ include "ds0.name" . }}-node
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "ds0.fullname" . }}-node
  labels:
    app: {{ include "ds0.name" . }}-node
  annotations:
    {{- with .Values.podAnnotations }}
      {{- toYaml . | nindent 8 }}
    {{- end }}
spec:
  replicas: {{ .Values.replicaCountNode }}
  selector:
    matchLabels:
      app: {{ include "ds0.name" . }}-node
  serviceName: {{ include "ds0.fullname" . }}-node-headless
  template:
    metadata:
      labels:
        app: {{ include "ds0.name" . }}-node
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
      containers:
        - name: {{ .Chart.Name }}-node
          image: "{{ .Values.image.repositoryNode }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
          - name: http
            containerPort: {{ .Values.containerPort }}
            protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
          - name: {{ include "ds0.fullname" . }}
            mountPath: {{ .Values.volumeMountPath }}
          env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name

  volumeClaimTemplates:
  - metadata:
      name: {{ include "ds0.fullname" . }}
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: {{ .Values.storageSize }}
