apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ds0.fullname" . }}-ns
  labels:
    app: {{ include "ds0.name" . }}-ns
spec:
  replicas: {{ .Values.replicaCountNS }}
  selector:
    matchLabels:
      app: {{ include "ds0.name" . }}-ns
  template:
    metadata:
      labels:
        app: {{ include "ds0.name" . }}-ns
    spec:
      containers:
        - name: {{ .Chart.Name }}-ns
          image: "{{ .Values.image.repositoryNS }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.containerPort }}
              protocol: TCP
          env:
          - name: NS_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ds0.fullname" . }}-ns
  labels:
    app: {{ include "ds0.name" . }}-ns
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.port }}
    protocol: TCP
    name: http
  selector:
      app: {{ include "ds0.name" . }}-ns