# go-tests-job.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "ds0.fullname" . }}-test
spec:
  backoffLimit: 0
  template:
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
      containers:
      - name: test
        image: "{{ .Values.image.repositoryTest }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
      restartPolicy: Never
