on: [push, pull_request]
name: test
jobs:
  test:
    runs-on: self-hosted
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: build and push
      run: make docker
    - name: helm uninstall
      run: helm uninstall ds0 -n ds0-test || true
    - name: helm install
      run: helm install ds0 ./deployment/ds0 -n ds0-test
    timeout-minutes: 5